/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js in normal projects.
// It is included here so the skeleton is immediately type-aware.
